#!/bin/bash


DIR=$( cd "$( dirname "$0" )" && pwd )

sudo apt update
sudo apt install git vim vim-gtk curl guake xclip build-essential ack-grep python-dev cmake

echo 'Python things...'
wget -c https://bootstrap.pypa.io/get-pip.py -P /tmp
sudo python /tmp/get-pip.py
sudo pip install virtualenvwrapper ipython ipdb httpie pyflakes jedi
cp pip/flake8 ~/.config

echo 'Go things...'
wget -c https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz -P /tmp
tar zxvf /tmp/go1.8.linux-amd64.tar.gz -C ~/.local/

echo 'Misc things...'
mkdir -p ~/Projects/go


echo 'Downloading requirements...'
if [[ ! -e $DIR/solarized/guake ]]; then
  echo '-> Guake colors ...'
  git clone https://github.com/coolwanglu/guake-colors-solarized.git $DIR/solarized/guake
  $DIR/solarized/guake/set_dark.sh
fi
if [[ ! -e $DIR/solarized/gnome ]]; then
  echo '-> Gnome colors ...'
  git clone https://github.com/sigurdga/gnome-terminal-colors-solarized -b python-dev $DIR/solarized/gnome
  $DIR/solarized/gnome/install.sh -s dark -p Solarized
  $DIR/solarized/gnome/solarize dark
fi
if [[ ! -e $DIR/solarized/dircolors ]]; then
  echo '-> Dir colors ...'
  git clone https://github.com/seebi/dircolors-solarized $DIR/solarized/dircolors-pack
  ln -fs $DIR/solarized/dircolors-pack/dircolors.ansi-dark $DIR/solarized/dircolors
fi
if [[ ! -e $DIR/apps/t ]]; then
  echo '-> Task manager ...'
  git clone https://github.com/sjl/t/ $DIR/apps/t
fi

ln -fs $DIR/bash_profile   ~/.bash_profile
ln -fs $DIR/bashrc         ~/.bashrc
ln -fs $DIR/gitconfig      ~/.gitconfig
ln -fs $DIR/pip            ~/.pip
ln -fs $DIR/gitconfig      ~/.gitconfig
ln -fs $DIR/vim            ~/.vim
ln -fs $DIR/vim/vimrc      ~/.vimrc

echo 'Reloading...'
source ~/.bashrc
