#!/bin/bash

DIR=$( cd "$( dirname "$0" )" && pwd )

sudo apt-get update
sudo apt-get install build-essential vim vim-gtk curl ack-grep guake aptitude xclip

echo 'Downloading requirements...'
if [[ ! -e $DIR/bash_completion/django_admin ]]; then
  echo '-> django_admin completion ...'
  curl -s 'https://raw.github.com/django/django/master/extras/django_bash_completion' > $DIR/bash_completion/django_admin
fi
if [[ ! -e $DIR/solarized/guake ]]; then
  echo '-> Guake colors ...'
  git clone https://github.com/coolwanglu/guake-colors-solarized.git $DIR/solarized/guake
  $DIR/solarized/guake/set_dark.sh
fi
if [[ ! -e $DIR/solarized/gnome ]]; then
  echo '-> Gnome colors ...'
  git clone https://github.com/sigurdga/gnome-terminal-colors-solarized $DIR/solarized/gnome
  $DIR/solarized/gnome/install.sh -s dark -p Solarized
  $DIR/solarized/gnome/solarize dark
fi
if [[ ! -e $DIR/solarized/dircolors ]]; then
  echo '-> Dir colors ...'
  git clone https://github.com/seebi/dircolors-solarized $DIR/solarized/dircolors-pack
  ln -fs $DIR/solarized/dircolors-pack/dircolors.ansi-dark $DIR/solarized/dircolors
fi

ln -fs $DIR/bash_profile   ~/.bash_profile
ln -fs $DIR/bashrc         ~/.bashrc
ln -fs $DIR/gitconfig      ~/.gitconfig
ln -fs $DIR/pip            ~/.pip
ln -fs $DIR/gitconfig      ~/.gitconfig
ln -fs $DIR/vim            ~/.vim
ln -fs $DIR/vim/vimrc      ~/.vimrc
